# Generated by Django 5.1.1 on 2024-10-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_details_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='product_details',
        ),
    ]
